blank_issues_enabled: false
contact_links:
  - name: â“ Question
    url: https://github.com/TeamOpenTube/OpenTube/discussions/new?category=questions
    about: Ask about anything OpenTube-related
  - name: ğŸ’¬ Matrix
    url: https://matrix.to/#/#opentube:matrix.opentube-ev.de
    about: Chat with us via Matrix for quick Q/A
  - name: ğŸ’¬ IRC
    url: https://web.libera.chat/#opentube
    about: Chat with us via IRC for quick Q/A
